### PR TITLE
Authentication PR

### PR DESCRIPTION
**Pull request by kenderb**
**Authentication and Posts** 

- Create a Post model and a Posts controller.
- Use a #before_action to restrict access to the #new and #create methods. 
- Write a very simple form in the app/views/posts/new.html.erb .
- Add logic in your Index view to display the author’s name, but only if I sign a user in.
- We sign in and create a few secret posts.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @kenderb and @kcotrinam 
### You have done really well so far :clap: However, you have a few issues to fix:-
- [x] There are issues with linting both rubocop and stylelint. Add all the required files, install all the required dependencies and configure properly. [Follow this guide for help](https://github.com/microverseinc/linters-config/tree/master/ror)
- [x] Update the routes files to include the actions passed in the controller. It creates the application routes using resources :posts, only: [:new, :create, :index]
- [x] When logged out, you do not need to show the CRUD operations(Show, edit, destroy), hide them. Only show them when logged in
### Make the changes and submit the project for another code review. Good luck.
- Happy coding!

**Comment by kcotrinam** [comment]
Thanks for the suggestions.
Nevertheless, we have completed the first and second change request because we found a contradiction in the third with the second one since if we only use routes index "new, :create, :index" as required, we won't be able to show the CRUD in the index.

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED ♻️ 

A great job implementing the requested changes 👏 
Just a few more things and ready to go! 💪  Do not worry, the code is good, just to make the project a bit more professional
Check my comments below and resubmit your project when are done
Good luck! 😄 
## Mandatory changes
- Add your usernames in the readme file in the Linkedin field
- Your project is not using PostgreSQL, kindly remove the information related in your getting started section
- Add a license to your project, preferably MIT
## Optional
- Fill up the about section in your GitHub profile, it will make the users easily know what is this project about, remember to add tags

**Review by javitocor — APPROVED** [review]
# STATUS APPROVED ⭐ 🥇 

Good job implementing the changes! 👏 
But I can see you have not filled up the about section in the Github repo! 🤔 
Anyway, you have met all the basic requirement, congratulations! 🥳 
Remember to fill up the completion form 📑  and you can move into the next project! ⏩ 
Good luck with it! 😃

**Pull request merged**
